matrix:
  include:

  - language: node_js
    node_js:
    - node

  - language: python
    python: 2.7
    install: pip install -r requirements.txt
    script:
    - pycodestyle .
    - python -m unittest discover -p "*_test.py"

  - language: bash
    services:
    - docker
    script: ./ci_container.sh

  - language: go
    install:
    - go get -t ./...
    - go get -u github.com/golang/lint/golint
    script:
    - go test -v ./...
    - "$GOPATH/bin/golint -set_exit_status"

env:
  matrix:
  - secure: rTnHDtfEuHiswgJ9UFTS2OgdzwxsmP42Sr6ci29kUM7ffGGd1u5dzliHHXK9Dcvm7OMXgsu0bVYY61C0+vpu7s4u8QopcV5ZddTKQwkRoNjxXJq8AW2gReytDwc5FBs37Nwl30UIK3W5sZrwOoPs+NfEqi4eavB26OSb9bO3Yo5GLE/jw3i8GFf+wrBegCNiVChYSZepnaC+xBD+l5lJZi5+MLFV+UNwNj93/Zv8VLLjhiv4iI0vM+U5ssqh1gyrR/n0cZpCFu7Do/tg/hpZkiwlP/FZP/qsAZjfYJpzpyjn587wHXHIL4muJ5UosYmRctf9x2NeQWo2WwUNuNdOKLdDX5lZY3VNaaITr6aAPoY8JnekFOa6gRfKQqeiaWGWslraAWV6GhxkUYxCiHh6Tk7V+IsDi6HLtVHvT6K+dvxjsZT7O1iynSSluwTAR+YBZuPKUJ+eG5H/Y45z/XPPW+l6oGW7qv99UE7072BNQYHXKooMtWY4fwE2NAXIxBBj4AiJVJ7G4doflSukMibR0LeBtRi7IMgvNuyKmD3G/vSGHVGccDVBGlSjPKBkmoWRVn1lRbsQhKjonbKtv1oFCqN8PpTCh1ywXcOD5U45NcKIiECwHRCmuMvrRfrOiWkZIwWZIErXFb8sHlxnw5fvgPL5u+k6BqsbMuaIee/xlcc=
  - secure: B1wlKOWtyHZv4JqMDpy/E4KrHY9jHMBbk8aw3Ljfq69D1eQH5MFjCdhLrKmF/1zdGJpnuccI5fEcAJIjeovP/F/TODiMREYwnR3WbikhSfjoel6SuJQN1drsjW7QOv0KA/R6rcxyTiem8ntuWztr/euaVmrS2S1plQMoPxqqEYOySETKHxHuGpXky5XH7ySQRFg89nY846rjLGWYo5NWQVCK6okqinMK0/vGjCxCwBx2BIvUGS/UwSkcxv91fM8MWGZO8Dhyo3UIKJyCvSOoDIJWjhOYb0DT7yXXndQtm7g5QVkCgv7YHKi4cZXnT6ISXuLLcgvy/n7+yq+zWgjk8cv/po0x434rhqQEfEbg6FhSDXCiWKd8J5HNGAPKgROUOqgn44FktV+wwT9eGToHPGo7X6sitM57Ku0tPZd23sgoexNlAEPp1+YvRaGSdB+WK3dsxWd0wB0/JnlQuuI33qOdjUjh4NBBpjr572zTFGR7NztkovKN8X9OUYMvrndEhFxMwxavqKEYGWY3gdIFx99SVdeCefOhP/3vs2eLMpr+87TpbA/B9CZkbZI9uTsd344rFO2amMg+3/LG+oYCVHwzM2FAwhsTlwKmsQWhbzOulhEn467XDHe+yLySZVPROUB8yI23iDZY5IgapPexNjTbaLij4kPQz8ozx2BmPSg=
